services:
  bot:
    build:
      target: dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/pyproject.toml
    restart: unless-stopped
    command: sh -c "alembic upgrade head && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python3 -m bot.main"

  api:
    build:
      target: dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/pyproject.toml
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: sh -c "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python3 -m api.main"

  frontend:
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json
    ports:
      - "5173:5173"
    restart: unless-stopped
    command: npm run dev -- --host
    labels:
      - traefik.http.services.frontend.loadbalancer.server.port=5173

  db:
    ports:
      - "5432:5432"
    restart: unless-stopped
      
  traefik:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    labels: !override
      - traefik.enable=true
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-dashboard-http.service=api@internal
      - traefik.http.routers.traefik-dashboard-https.service=api@internal
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
      - traefik.http.middlewares.compress.compress=true
    command: 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--accesslog"
      - "--api"
      - "--log"
      - "--log.level=DEBUG"

volumes:
  postgres_data:
  mongo_data:
