version: '3.8'

services:
  bot:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    user: "1000:1000"
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python3 main.py

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data: