version: '3.8'

services:
  bot:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    user: "1000:1000"
    command: python main.py

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: