version: '3.8'

services:
  bot:
    build:
      context: .
      target: production
    env_file:
      - .env.prod
    depends_on:
      - db
    user: "${UID}:${GID}"
    command: python main.py
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
