"""Add report table

Revision ID: 258163e42b29
Revises: bf755a8c00c5
Create Date: 2025-01-07 05:03:45.659392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "258163e42b29"
down_revision: Union[str, None] = "bf755a8c00c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "pending",
        "reviewing",
        "pending_info",
        "valid",
        "invalid",
        "resolved",
        "closed",
        name="reportstatustypes",
    ).create(op.get_bind())
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "reviewing",
                "pending_info",
                "valid",
                "invalid",
                "resolved",
                "closed",
                name="reportstatustypes",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["user_account.id"],
            name=op.f("fk_report_from_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["user_account.id"],
            name=op.f("fk_report_to_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report")),
    )
    op.create_index(
        op.f("ix_report_from_user_id"), "report", ["from_user_id"], unique=False
    )
    op.create_index(op.f("ix_report_status"), "report", ["status"], unique=False)
    op.create_index(
        op.f("ix_report_to_user_id"), "report", ["to_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_to_user_id"), table_name="report")
    op.drop_index(op.f("ix_report_status"), table_name="report")
    op.drop_index(op.f("ix_report_from_user_id"), table_name="report")
    op.drop_table("report")
    sa.Enum(
        "pending",
        "reviewing",
        "pending_info",
        "valid",
        "invalid",
        "resolved",
        "closed",
        name="reportstatustypes",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
