"""Allow cascading 2

Revision ID: 281ee6809e1d
Revises: 0da5eeef72c5
Create Date: 2025-02-05 19:08:31.703324

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "281ee6809e1d"
down_revision: Union[str, None] = "0da5eeef72c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_reaction_from_user_id"), "reaction", ["from_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_reaction_to_user_id"), "reaction", ["to_user_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_reaction_from_user_id"), "reaction", ["from_user_id", "to_user_id"]
    )
    op.create_foreign_key(
        op.f("fk_reaction_to_user_id_user_account"),
        "reaction",
        "user_account",
        ["to_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_reaction_from_user_id_user_account"),
        "reaction",
        "user_account",
        ["from_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_report_from_user_id"), "report", ["from_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_to_user_id"), "report", ["to_user_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_report_to_user_id_user_account"),
        "report",
        "user_account",
        ["to_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_report_from_user_id_user_account"),
        "report",
        "user_account",
        ["from_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_user_media_user_id"), "user_media", ["user_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_user_media_user_id"), "user_media", ["user_id", "file_id"]
    )
    op.create_foreign_key(
        op.f("fk_user_media_user_id_user_account"),
        "user_media",
        "user_account",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"),
        "user_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_foreign_key(
        op.f("fk_user_preferences_user_id_user_account"),
        "user_preferences",
        "user_account",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_preferences_user_id_user_account"),
        "user_preferences",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_constraint(
        op.f("fk_user_media_user_id_user_account"), "user_media", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_user_media_user_id"), "user_media", type_="unique")
    op.drop_index(op.f("ix_user_media_user_id"), table_name="user_media")
    op.drop_constraint(
        op.f("fk_report_from_user_id_user_account"), "report", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_report_to_user_id_user_account"), "report", type_="foreignkey"
    )
    op.drop_index(op.f("ix_report_to_user_id"), table_name="report")
    op.drop_index(op.f("ix_report_from_user_id"), table_name="report")
    op.drop_constraint(
        op.f("fk_reaction_from_user_id_user_account"), "reaction", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_reaction_to_user_id_user_account"), "reaction", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_reaction_from_user_id"), "reaction", type_="unique")
    op.drop_index(op.f("ix_reaction_to_user_id"), table_name="reaction")
    op.drop_index(op.f("ix_reaction_from_user_id"), table_name="reaction")
    # ### end Alembic commands ###
