"""Add preferences

Revision ID: 4e5ca2b16f49
Revises: bf07d6322c9b
Create Date: 2025-01-06 12:15:58.650548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5ca2b16f49'
down_revision: Union[str, None] = 'bf07d6322c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('telegram_unique_id', sa.String(), nullable=True),
    sa.Column('telegram_path', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_telegram_id'), 'file', ['telegram_id'], unique=False)
    op.create_table('user_media',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'file_id'),
    sa.UniqueConstraint('user_id', 'file_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('preferred_gender', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_max_age'), 'user_preferences', ['max_age'], unique=False)
    op.create_index(op.f('ix_user_preferences_min_age'), 'user_preferences', ['min_age'], unique=False)
    op.create_index(op.f('ix_user_preferences_preferred_gender'), 'user_preferences', ['preferred_gender'], unique=False)
    op.add_column('user_account', sa.Column('gender', sa.String(length=1), nullable=False))
    op.add_column('user_account', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user_account', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('user_account', sa.Column('ui_language', sa.String(length=2), server_default=sa.text("'en'"), nullable=False))
    op.alter_column('user_account', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_account_age'), 'user_account', ['age'], unique=False)
    op.create_index(op.f('ix_user_account_gender'), 'user_account', ['gender'], unique=False)
    op.create_index(op.f('ix_user_account_telegram_id'), 'user_account', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_telegram_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_gender'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_age'), table_name='user_account')
    op.alter_column('user_account', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user_account', 'ui_language')
    op.drop_column('user_account', 'longitude')
    op.drop_column('user_account', 'latitude')
    op.drop_column('user_account', 'gender')
    op.drop_index(op.f('ix_user_preferences_preferred_gender'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_min_age'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_max_age'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('user_media')
    op.drop_index(op.f('ix_file_telegram_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
