"""Update file table

Revision ID: 654db394ec78
Revises: 3d41c209db4d
Create Date: 2025-01-08 05:23:38.946066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654db394ec78'
down_revision: Union[str, None] = '3d41c209db4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('file', sa.Column('thumbnail_id', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_file_thumbnail_id_file'), 'file', 'file', ['thumbnail_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_file_thumbnail_id_file'), 'file', type_='foreignkey')
    op.drop_column('file', 'duration')
    op.drop_column('file', 'thumbnail_id')
    op.drop_column('file', 'mime_type')
    op.drop_column('file', 'file_size')
    # ### end Alembic commands ###
