"""Update file table

Revision ID: 8636dd26ea85
Revises: f1d4e685a9f0
Create Date: 2025-01-08 06:06:46.600080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8636dd26ea85"
down_revision: Union[str, None] = "f1d4e685a9f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "telegram_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(length=16),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "telegram_id",
        existing_type=sa.String(length=16),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
