"""Add phone_number to user_account

Revision ID: 8b3f3d4f150e
Revises: b0186e7a6e10
Create Date: 2025-01-21 16:38:24.826355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b3f3d4f150e"
down_revision: Union[str, None] = "b0186e7a6e10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "phone_number")
    # ### end Alembic commands ###
