"""Remove unique constraint from place_id

Revision ID: 8ba7b8c5f9a5
Revises: 5606164a5c28
Create Date: 2025-02-10 12:19:05.810430

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ba7b8c5f9a5"
down_revision: Union[str, None] = "5606164a5c28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_account_place_id", table_name="user_account")
    op.create_index(
        op.f("ix_user_account_place_id"), "user_account", ["place_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_account_place_id"), table_name="user_account")
    op.create_index(
        "ix_user_account_place_id", "user_account", ["place_id"], unique=True
    )
    # ### end Alembic commands ###
