"""Add is_location_precise in user_account

Revision ID: a9684b196915
Revises: 8ba7b8c5f9a5
Create Date: 2025-02-26 12:19:42.735836

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9684b196915"
down_revision: Union[str, None] = "8ba7b8c5f9a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column(
            "is_location_precise",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "is_location_precise")
    # ### end Alembic commands ###
