"""Add default status to report

Revision ID: acc2841875cf
Revises: 660fdb5d0c32
Create Date: 2025-01-14 13:55:17.592270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acc2841875cf'
down_revision: Union[str, None] = '660fdb5d0c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'status',
               existing_type=postgresql.ENUM('pending', 'reviewing', 'pending_info', 'valid', 'invalid', 'resolved', 'closed', name='reportstatustypes'),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'status',
               existing_type=postgresql.ENUM('pending', 'reviewing', 'pending_info', 'valid', 'invalid', 'resolved', 'closed', name='reportstatustypes'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
