"""Make phone_number required

Revision ID: ae1b6a06cfff
Revises: 8b3f3d4f150e
Create Date: 2025-01-21 16:52:02.710964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae1b6a06cfff"
down_revision: Union[str, None] = "8b3f3d4f150e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_account", "phone_number", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_account", "phone_number", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
