"""Change age to birth_date

Revision ID: b0186e7a6e10
Revises: cd4e08d68717
Create Date: 2025-01-18 13:00:51.712728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0186e7a6e10'
down_revision: Union[str, None] = 'cd4e08d68717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.drop_index('ix_user_account_age', table_name='user_account')
    op.drop_column('user_account', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_user_account_age', 'user_account', ['age'], unique=False)
    op.drop_column('user_account', 'birth_date')
    # ### end Alembic commands ###
