"""Update user

Revision ID: bf07d6322c9b
Revises: a196d45d5450
Create Date: 2025-01-06 07:32:42.581233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf07d6322c9b'
down_revision: Union[str, None] = 'a196d45d5450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('rating', sa.Integer(), server_default=sa.text('1400'), nullable=False))
    op.add_column('user_account', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_account', sa.Column('bio', sa.String(length=255), nullable=True))
    op.alter_column('user_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False)
    op.alter_column('user_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('user_account', 'bio')
    op.drop_column('user_account', 'is_active')
    op.drop_column('user_account', 'rating')
    # ### end Alembic commands ###
