"""Add reactions

Revision ID: bf755a8c00c5
Revises: 3cfd5ab2eef5
Create Date: 2025-01-06 13:43:56.069835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf755a8c00c5'
down_revision: Union[str, None] = '3cfd5ab2eef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('like', 'dislike', name='reactiontype').create(op.get_bind())
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', postgresql.ENUM('like', 'dislike', name='reactiontype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['user_account.id'], name=op.f('fk_reaction_from_user_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user_account.id'], name=op.f('fk_reaction_to_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction')),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name=op.f('uq_reaction_from_user_id'))
    )
    op.create_index(op.f('ix_reaction_from_user_id'), 'reaction', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_reaction_reaction_type'), 'reaction', ['reaction_type'], unique=False)
    op.create_index(op.f('ix_reaction_to_user_id'), 'reaction', ['to_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_media_user_id'), 'user_media', ['user_id', 'file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_media_user_id'), 'user_media', type_='unique')
    op.drop_index(op.f('ix_reaction_to_user_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_reaction_type'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_from_user_id'), table_name='reaction')
    op.drop_table('reaction')
    sa.Enum('like', 'dislike', name='reactiontype').drop(op.get_bind())
    # ### end Alembic commands ###
