"""Change PreferredGenders.friends to both

Revision ID: ccb85f49481b
Revises: a9684b196915
Create Date: 2025-03-03 13:25:35.953369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'ccb85f49481b'
down_revision: Union[str, None] = 'a9684b196915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='preferredgenders',
        new_values=['male', 'female', 'both'],
        affected_columns=[TableReference(table_schema='public', table_name='user_preferences', column_name='preferred_gender')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='preferredgenders',
        new_values=['male', 'female', 'friends'],
        affected_columns=[TableReference(table_schema='public', table_name='user_preferences', column_name='preferred_gender')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
