"""Add added_rating field to reaction

Revision ID: cd4e08d68717
Revises: a228992c6dd1
Create Date: 2025-01-18 08:56:29.031637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4e08d68717'
down_revision: Union[str, None] = 'a228992c6dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('added_rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reaction', 'added_rating')
    # ### end Alembic commands ###
