"""Remove telegram_path from file

Revision ID: f1d4e685a9f0
Revises: 654db394ec78
Create Date: 2025-01-08 05:37:42.496876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1d4e685a9f0"
down_revision: Union[str, None] = "654db394ec78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "telegram_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("telegram_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
