"""Add places

Revision ID: 1621442f509d
Revises: bd9bf7453ea4
Create Date: 2025-02-09 07:20:32.662165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1621442f509d"
down_revision: Union[str, None] = "bd9bf7453ea4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place")),
    )
    op.create_table(
        "place_name",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("place_id", sa.String(length=64), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM("uz", "ru", "en", name="uilanguages", create_type=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_place_name_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_name")),
    )
    op.create_index(
        op.f("ix_place_name_place_id"), "place_name", ["place_id"], unique=False
    )
    op.add_column("user_account", sa.Column("place_id", sa.String(), nullable=True))
    op.drop_column("user_account", "city_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column("city_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("user_account", "place_id")
    op.drop_index(op.f("ix_place_name_place_id"), table_name="place_name")
    op.drop_table("place_name")
    op.drop_table("place")
    # ### end Alembic commands ###
