"""Add ban table

Revision ID: 51f7d5532cfc
Revises: f889590c8711
Create Date: 2025-05-27 08:41:55.050833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f7d5532cfc'
down_revision: Union[str, None] = 'f889590c8711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ban'))
    )
    op.create_index(op.f('ix_ban_expires_at'), 'ban', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ban_user_telegram_id'), 'ban', ['user_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ban_user_telegram_id'), table_name='ban')
    op.drop_index(op.f('ix_ban_expires_at'), table_name='ban')
    op.drop_table('ban')
    # ### end Alembic commands ###
