"""empty message

Revision ID: 5606164a5c28
Revises: 1621442f509d
Create Date: 2025-02-09 09:39:31.488575

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5606164a5c28"
down_revision: Union[str, None] = "1621442f509d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_place_name_place_id"), "place_name", ["place_id", "language"]
    )
    op.create_index(
        op.f("ix_user_account_place_id"), "user_account", ["place_id"], unique=True
    )
    op.create_foreign_key(
        op.f("fk_user_account_place_id_place"),
        "user_account",
        "place",
        ["place_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_account_place_id_place"), "user_account", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_account_place_id"), table_name="user_account")
    op.drop_constraint(op.f("uq_place_name_place_id"), "place_name", type_="unique")
    # ### end Alembic commands ###
