"""Add indexes to user_account

Revision ID: 6d35e907d717
Revises: 2e3dc8d939a6
Create Date: 2025-07-25 09:55:35.494430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d35e907d717'
down_revision: Union[str, None] = '2e3dc8d939a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_account_gender'), 'user_account', ['gender'], unique=False)
    op.create_index(op.f('ix_user_account_is_active'), 'user_account', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_is_active'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_gender'), table_name='user_account')
    # ### end Alembic commands ###
