"""Add id field to user_media and preferences

Revision ID: 9079d0c73d23
Revises: cfdbd0c789fb
Create Date: 2025-01-10 07:01:33.082482

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9079d0c73d23"
down_revision: Union[str, None] = "cfdbd0c789fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_media DROP CONSTRAINT pk_user_media CASCADE")
    op.execute("ALTER TABLE user_media ADD COLUMN id SERIAL NOT NULL")
    op.create_primary_key("pk_user_media", "user_media", ["id"])
    op.create_index(
        op.f("ix_user_media_file_id"), "user_media", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_media_user_id"), "user_media", ["user_id"], unique=False
    )

    op.execute(
        "ALTER TABLE user_preferences DROP CONSTRAINT pk_user_preferences CASCADE"
    )
    op.execute("ALTER TABLE user_preferences ADD COLUMN id SERIAL NOT NULL")
    op.create_primary_key("pk_user_preferences", "user_preferences", ["id"])
    op.create_index(
        op.f("ix_user_preferences_user_id"),
        "user_preferences",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE user_preferences DROP CONSTRAINT pk_user_preferences CASCADE"
    )
    op.create_primary_key("pk_user_preferences", "user_preferences", ["user_id"])
    op.execute("ALTER TABLE user_media DROP CONSTRAINT pk_user_media CASCADE")
    op.execute(
        "ALTER TABLE user_media ADD CONSTRAINT pk_user_media PRIMARY KEY (user_id, file_id)"
    )
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_column("user_preferences", "id")
    op.drop_index(op.f("ix_user_media_user_id"), table_name="user_media")
    op.drop_index(op.f("ix_user_media_file_id"), table_name="user_media")
    op.drop_column("user_media", "id")
    # ### end Alembic commands ###
