"""Add is_match_notified field

Revision ID: a228992c6dd1
Revises: acc2841875cf
Create Date: 2025-01-17 10:40:22.490343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a228992c6dd1"
down_revision: Union[str, None] = "acc2841875cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reaction",
        sa.Column(
            "is_match_notified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reaction", "is_match_notified")
    # ### end Alembic commands ###
