"""Add city_name to user_account

Revision ID: bd9bf7453ea4
Revises: 3afc08e2c675
Create Date: 2025-02-08 15:23:08.842989

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd9bf7453ea4"
down_revision: Union[str, None] = "3afc08e2c675"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("city_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "city_name")
    # ### end Alembic commands ###
