"""Increate telegram_id size for files

Revision ID: cfdbd0c789fb
Revises: 8636dd26ea85
Create Date: 2025-01-08 06:38:13.802451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfdbd0c789fb"
down_revision: Union[str, None] = "8636dd26ea85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "telegram_id",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "file",
        "telegram_unique_id",
        existing_type=sa.VARCHAR(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "telegram_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=16),
        existing_nullable=True,
    )
    op.alter_column(
        "file",
        "telegram_unique_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
