name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into Azure VM and deploy
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.40.48.177 << 'EOF'
          # Stop and remove existing container
          cd anordating
          sudo docker stop anorcontainer || true
          sudo docker rm anorcontainer || true

          # Build the new Docker image
          sudo docker build -t anorimage .

          # Run the container with the .env file
          sudo docker run -d --env-file .env --name anorcontainer anorimage
        EOF

